version: '3.8'

services:
  web:
    build: ./app_flask
    ports:
      -  "5000:5000"
    volumes:
      - ./app_flask:/app
    env_file:
      - ./app_flask/.env.flask
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.db
    ports:
      - "5432:5432"
volumes:
  postgres_data: